name: Build PlotSquared

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build all modules
        run: ./gradlew clean build

      - name: Upload Bukkit jar
        uses: actions/upload-artifact@v3
        with:
          name: plotsquared-bukkit
          path: Bukkit/build/libs/*.jar
